sudo: false
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
env:
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin USE_DEB=true  USE_JENKINS=true NO_SUDO=true
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin USE_DEB=false USE_JENKINS=true NO_SUDO=true
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=true
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=false
  - ROS_DISTRO=jade   ROSWS=wstool BUILDER=catkin USE_DEB=true
  - ROS_DISTRO=jade   ROSWS=wstool BUILDER=catkin USE_DEB=false
matrix:
  allow_failures:
    - env: ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin USE_DEB=false USE_JENKINS=true NO_SUDO=true
    - env: ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=false
    - env: ROS_DISTRO=jade   ROSWS=wstool BUILDER=catkin USE_DEB=false
script: source .travis/travis.sh
